# -*- mode: Python -*-

# For more on Extensions, see: https://docs.tilt.dev/extensions.html
load('ext://restart_process', 'docker_build_with_restart')

local_resource(
  'compile-go',
  'CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o print-pods-in-default .',
  deps=['./main.go'],
)

# Build: tell Tilt what images to build from which directories
docker_build_with_restart(
    'print-pods-in-default',
    '.',
    entrypoint=['/print-pods-in-default'],
    dockerfile='./Dockerfile',
    only=['./print-pods-in-default'],
    live_update=[sync('./print-pods-in-default', '/print-pods-in-default')],
)

# Deploy: tell Tilt what YAML to deploy
k8s_yaml('deploy.yaml')
